export const APP_ROUTES = {
  home: "/",
  swap: "/swap",
  pool: "/pool",
  tokens: "/tokens",
  bridge: "/bridge",
  analytics: "/analytics",
  activity: "/activity",
  docs: "/docs",
  portfolio: "/portfolio",
  settings: "/settings",
} as const;

export const API_ROUTES = {
  health: "/api/v1/health",
  ready: "/api/v1/ready",
  networkStatus: "/api/v1/network/status",
  deploymentStatus: "/api/v1/deployment/status",
  prices: "/api/v1/prices",
  rates: "/api/v1/rates",
  pools: "/api/v1/pools",
  quote: "/api/v1/swap/quote",
  swapSettings: "/api/v1/swap/settings",
  swapConfig: "/api/v1/swap/config",
  swapReadiness: "/api/v1/swap/readiness",
  swapVerify: "/api/v1/swap/verify",
  tokenResolve: "/api/v1/tokens/resolve",
  trustedTokens: "/api/v1/tokens/trusted",
  preflight: "/api/v1/transactions/preflight",
  execute: "/api/v1/transactions/execute",
  transaction: (digest: string) => `/api/v1/transactions/${encodeURIComponent(digest)}`,
  sessionChallenge: "/api/v1/session/challenge",
  sessionVerify: "/api/v1/session/verify",
  sessionCurrent: "/api/v1/session/current",
  sessionLogout: "/api/v1/session/logout",
  wallet: (address: string) => `/api/v1/wallet/${encodeURIComponent(address)}`,
  walletActivity: (address: string) => `/api/v1/wallet/${encodeURIComponent(address)}/activity`,
  portfolio: (address: string) => `/api/v1/portfolio/${encodeURIComponent(address)}`,
  reconcile: "/api/v1/jobs/reconcile",
  cleanup: "/api/v1/jobs/cleanup",
} as const;
